spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mrmoore
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true

server:
  servlet:
    context-path: /api